services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # dataはボリュームマウント
    volumes:
      - ./data:/app/data
    
    